title: 3dmath
description: >- # this means to ignore newlines until "baseurl:"
  A math library for building 3D apps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "mdh81.github.io/3dmath/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mdh81

# Build settings
theme: "minima" 
plugins:
  - jekyll-feed
