title: 3dmath
description: >- 
  A math library for building 3D apps.
baseurl: ""
url: "https://mdh81.github.io/3dmath/" 
github_username: mdh81

# Build settings
remote_theme: "pmarsceill/just-the-docs" 
plugins:
  - jekyll-feed
